ifndef::image_fmt[]
:image_fmt: svg
endif::[]
:toc: yes
:toclevels: 4
:stem:
:sectnums:
:sectnumlevels: 0
:icons: font
:homedir: .
//:imagesdir: images
:docinfo: shared
:press: article
:linkcss:
ifdef::html[]
:staticimgdir: ../images/bank/original/static
:svgimgdir: ../images/vector
endif::[]
ifndef::html[]
:staticimgdir: ../_images/bank/original/static
:svgimgdir: ../_images/vector
endif::[]
:doubleslash: //
:enterkey: enter key &#x21B5;
:enterkeyshort: &#x21B5;
:arrowupkey: &#x2191;
:arrowdownkey: &#x2193;
:homekey: &#x21F1;
:endkey: &#x21F2;
:pageupkey: &#x21DE;
:pagedownkey: &#x21DF;
:exampleimagewidth_smallscreen: 70%
:paypal: https://www.paypal.com/donate/?hosted_button_id=G2QSV9ZD4EB4A
:patreon: https://www.patreon.com/14930736/join
:appdir: /home/michel/riffian/Data/Data/admin/linux/shotplan

== Overview 

shotplan is a tool for implementing full application test benches with automated test execution, output verification and reporting incl. screenshooting and video capturing.

The tests are run in sequence from a test plan file in YAML format, in which tests are programmed and controlled via bash scriptlets. 

A test plan splits into a sequence of test cases, in which a sequence of numbered test steps are defined. 

shotplan reports about each executed test step and its result on the standard output, including a timestamped identification banner which specifies version and revision control numbers of tested items, test tools and dependencies.

Shotplan takes its name from the fact that the tool is also capable of producing screenshots and video captures for executed tests.

NOTE: The test plan file can hold any name, but by convention it is usually 'shotplan.yml'

== Target applications

shotplan is initially designed and used to automate tests for system commands and user CLI applications. 

Notwithstanding, thanks to graphical automation tool like `xdotool`, it is perfectly foreseeable to test graphical application by triggering mouse and keyboard events. 

NOTE: A full automated test process of a graphical app would also require to compare the graphical output with a reference image. This feature is not available yet.

== Installation

Shotplan installs in `/usr/bin/shotplan/`.

Dependencies are generally automatically installed by shotplan at runtime, with the exception of the biggest ones: imagemagick, obs-studio, vlc, for the following reasons:

* Leave the choice for tester not seeking to produce screenshots and videos and thereby not installing those tools
* Avoid automatic (failing) installation in docker container where it is not relevant anyway

[source,bash,title="Debian system package (requires root rights)"]
----
sudo apt install imagemagick    # For making screenshots
sudo apt install obs-studio     # For video captures
sudo apt install vlc            # For visualizing video captures

wget https://slashetc.fr/download/shotplan_1.1-1_amd64.deb 
sudo dpkg -i shotplan_1.1-1_amd64.deb
----

== Documentation

Please check the official documentation at https://slashetc.fr/en/developertoolsforlinux/shotplan/ that develops the following aspects:

* Test reporting format
* Test plan file format
* Test plan execution workflow
* Other information...

== References

Shotplan was used to validate the following tools:

* link:https://slashetc.fr/en/developertoolsforlinux/arcv/arcv_documentation.html#_testing[arcv revision control tool,window=_blank]
* link:https://slashetc.fr/en/products/mountpilot/mountpilot_documentation.html#_testing[mountpilot,window=_blank]

== Man page

[code, role="css-manpage"]
----
SHOTPLAN(1)                      User Commands                     SHOTPLAN(1)

NAME
       Shotplan  -  Test  plan execution tool providing screenshots and videos
       reporting

SYNOPSIS
       shotplan OPTIONS [ <SHOTPLAN PATH> [ <PLAN NAME> [ ANY ] ] ]

       Arguments:

       <plan file path>

              The shotplan file where the tests are defined (YAML format)

       [<plan name>]

              Optional: the name of the test (shot) plan to  execute  (instead
              of all).

       [<any string>]

              Optional:  the providing of any third argument indicates only to
              run the last step of the specified shot plan.

       OPTIONS:

       --cat

              List available categories

       --debug

              Activates debug logs

       --force-defaults

              Forces default values for required user input to be used and  do
              not ask user to enter a value

       --from =STRING

              The test plan from which to start the test execution

       -C =STRING

              Test category to run

       -F, --filelist

              Prints  the  list  of  output  files (images and videos) as they
              would have been generated during plan execution.

       -M, --manpage

              Generates command samples for manpages based on the shot plan

       -P, --planids

              Prints the logical Ids of all defined test plans.

       -R, --report

              Switch on generation of the AsciiDoc report fragments which  in‐
              clude screenshots and videos

       -T, --no-report

              Switch off generation of the AsciiDoc report fragments which in‐
              clude screenshots and videos (default)

       -a

              Switch off interactivity

       -i

              Switch on interactivity (default)

       -y

              Assume 'Yes' when prompted for confirmation

DESCRIPTION
       shotplan is a test execution and reporting tool which enables to define
       and execute tests launched and controlled by script.

       The tests to run and the control scripts are defined in a YAML configu‐
       ration file where the sequence of tests are defined and  programmed  in
       script.  The YAML file is also called test plan or shot plan, and is by
       convention named .

       A test plan splits into a sequence of  test  cases  (also  called  test
       plans), in which a sequence of test steps are defined.

       shotplan  reports  about each executed test and its result on the stan‐
       dard output, including a dated test banners indicating version and  re‐
       vision control numbers of tested items, test tools and dependencies.

       Shotplan takes its name by the fact that the tool is capable of produc‐
       ing screenshots and video captures for executed tests.

EXAMPLES
       Testing with reporting (screenshots)

              $ shotplan --report

       Testing without reporting

              $ shotplan --T

       Testing starting from a certain plan, use option --from, e.g

              $ shotplan --from-init

AUTHOR
       Written by Michel MEHL

REPORTING BUGS
       Report bugs to <michel.mehl@slashetc.fr>

COPYRIGHT
       Copyright © 2026 Michel MEHL. All rights reserved.

       License terms written down in file LICENSE.txt

Shotplan 1.1.1                  septembre 2026                     SHOTPLAN(1)

----